### ISSUE TITLE
Rate locations

### ISSUE THREAD

**Issue by fatdzo** [cforlando/orlando-walking-tours-android#11]
Allow users to rate locations (1-5 stars)

**Comment by quicodesfor** [comment]
This is very subjective because many different people have different tastes as well as drive people from exploring landmarks with "low" ratings. It would also require an endpoint to collect ratings, someone to vet ratings in case of abuse, and other issues related to user input.
The best way to "rate" a location would be to allow users to post to their social media accounts about a location where this app would provide a template with location (and other relevant) information.
I say axe this feature.
